import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import indianFlag from "../images/ind_flag.png";
import NicLogo from "../images/nic_logo3.svg";
import NicLogo2 from "../images/nic_logo2.png";
import Footer from "../components/Footer";

const TermsOfService = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-gray-200 ">
      {/* Navbar */}
      <nav className="fixed w-full z-50 bg-white shadow text-[#003366]">
        <div className="bg-[#003366] text-white text-xs sm:text-sm py-2">
          <div className="max-w-screen-2xl mx-auto flex justify-between items-center px-4 sm:px-6 xl:px-20">
            <div className="flex items-center space-x-2">
              <img
                src={indianFlag}
                alt="Indian Flag"
                className="w-6 h-4 sm:h-6"
              />
              <span className="font-medium">
                भारत सरकार | Government of India
              </span>
            </div>
            <div className="flex items-center space-x-3 sm:space-x-4">
              <a
                href="#main-content"
                className="hidden sm:block hover:underline"
              >
                Skip to Content
              </a>
              <div className="flex items-center space-x-1">
                <button className="text-xs font-semibold">A+</button>
                <button className="text-xs font-semibold">A</button>
                <button className="text-xs font-semibold">A-</button>
              </div>
            </div>
          </div>
        </div>

        <div className="max-w-screen-2xl mx-auto flex justify-between items-center px-4 sm:px-6 xl:px-20 py-5">
          <Link to="/">
            <div className="flex items-center space-x-6">
              <img
                src={NicLogo}
                alt="NIC Logo"
                className="w-[220px] object-contain"
              />
              <h1 className="text-2xl sm:text-4xl font-bold tracking-wide">
                AI MEDHA
              </h1>
            </div>
          </Link>
          <div className="hidden sm:flex items-center space-x-6 text-base">
            <ul className="flex space-x-5">
              <li>
                <a href="#about" className="hover:text-[#FF9933]">
                  About
                </a>
              </li>
              <li>
                <a href="#features" className="hover:text-[#FF9933]">
                  Features
                </a>
              </li>
              <li>
                <a href="/services" className="hover:text-[#FF9933]">
                  Services
                </a>
              </li>
              <li>
                <a href="#contact" className="hover:text-[#FF9933]">
                  Contact
                </a>
              </li>
              <li>
                <Link to="/auth/login" className="hover:text-[#FF9933]">
                  Login
                </Link>
              </li>
              <li>
                <Link to="/auth/register" className="hover:text-[#FF9933]">
                  Register
                </Link>
              </li>
            </ul>
            <img
              src={NicLogo2}
              alt="NIC Secondary Logo"
              className="w-[140px] object-contain"
            />
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main
        id="main-content"
        className="w-full pt-48 pb-16 px-4 sm:px-6 lg:px-20"
      >
        <div className="max-w-screen-xl mx-auto bg-white p-8 sm:p-10 rounded-lg ">
          <h2 className="text-3xl font-bold text-blue-800 mb-6">
            Terms and Conditions
          </h2>

          <p className="text-base text-gray-700 mb-6 leading-relaxed">
            <strong>Disclaimer:</strong>
            <br></br>
            This system is intended for demonstration purposes only. The
            outcomes generated by this system are not intended for use with
            external services or third-party applications. Users are advised
            that the system is designed in compliance with the applicable laws
            of the land.
          </p>

          <div className="space-y-5 text-base text-gray-800 leading-relaxed">
            <div>
              <strong className="text-gray-700">1. Acceptance of Terms:</strong>{" "}
              <br></br>
              By accessing and using this system, you agree to be bound by these
              terms and conditions. If you do not agree to these terms, please
              do not use this system.
            </div>
            <div>
              <strong className="text-gray-700">2. Purpose and Usage:</strong>{" "}
              <br></br>
              This system is provided for demonstration purposes only. The
              outcomes generated by this system are not intended for use with
              external services or third-party applications. Any use of the
              system for purposes other than demonstration is strictly
              prohibited.
            </div>
            <div>
              <strong className="text-gray-700">
                3. Compliance with Laws:
              </strong>{" "}
              <br></br>
              Users are advised that the system is designed in compliance with
              the applicable laws of the land. Users are responsible for
              ensuring that their use of the system complies with all applicable
              local, state, national, and international laws and regulations.
            </div>
            <div>
              <strong className="text-gray-700">
                4. Limitation of Liability:
              </strong>{" "}
              <br></br>
              In no event shall we be liable for any direct, indirect,
              incidental, special, or consequential damages arising out of or in
              connection with the use or inability to use the system, even if we
              have been advised of the possibility of such damages.
            </div>
            <div>
              <strong className="text-gray-700">
                5. Changes to the Terms:
              </strong>{" "}
              <br></br>
              We reserve the right to modify these terms and conditions at any
              time. Any changes will be effective immediately upon posting on
              this page. Your continued use of the system after any changes
              signifies your acceptance of the new terms.
            </div>
            <div>
              <strong className="text-gray-700">6. Contact Information:</strong>{" "}
              <br></br>
              If you have any questions or concerns about these terms and
              conditions, please contact us at:
              <a
                href="mailto:support@aimedha.gov.in"
                className="text-blue-600 underline"
              >
                support@aimedha.gov.in
              </a>
              .
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default TermsOfService;
